name: IPTV M3U 每天自动更新

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的git历史

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Check Pipfile format
        run: |
          if [ -f "Pipfile" ]; then
            echo "Starting to check Pipfile format..."
            pip install toml
            set +e
            python -c "import toml; toml.load(open('Pipfile'))"
            check_status=$?
            set -e
            if [ $check_status -eq 0 ]; then
              echo "Pipfile format is valid."
            else
              echo "Pipfile format is invalid. Here is the content of Pipfile:"
              cat Pipfile
              exit 1
            fi
          else
            echo "Pipfile not found in the project directory. Please ensure it exists."
            exit 1
          fi

      - name: Install pipenv
        run: |
          echo "Installing pipenv..."
          pip install pipenv
          if [ $? -ne 0 ]; then
            echo "Failed to install pipenv. Please check the network or Python environment."
            exit 1
          fi

      - name: Install dependencies
        run: |
          echo "Installing project dependencies..."
          pipenv install --deploy
          if [ $? -ne 0 ]; then
            echo "Failed to install project dependencies. Check Pipfile or network."
            exit 1
          fi

      - name: Install FFmpeg
        run: |
          echo "Installing FFmpeg..."
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          if [ $? -ne 0 ]; then
            echo "Failed to install FFmpeg. Check system permissions or network."
            exit 1
          fi

      - name: Generate M3U and TXT files
        run: |
          if [ -f "main.py" ]; then
            echo "Running main.py to generate M3U and TXT files..."
            pipenv run python main.py 2>&1 | tee main.log
            if [ $? -ne 0 ]; then
              echo "Failed to generate M3U and TXT files. Check main.py or dependencies."
              echo "Check main.log for detailed error messages."
              cat main.log
              exit 1
            fi
            # 检查所有需要的文件是否生成
            required_files=(
              "output/result.m3u"
              "output/result.txt"
              "output/result_http_test.m3u"
              "output/result_http_test.txt"
            )
            for file in "${required_files[@]}"; do
              if [ ! -f "$file" ]; then
                echo "File $file was not generated. Check main.log for details."
                cat main.log
                exit 1
              fi
            done
          else
            echo "Script file main.py not found. Please ensure it exists."
            exit 1
          fi

      - name: Update README.md
        run: |
          # 获取当前时间
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          
          # 获取仓库信息
          repo_owner=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
          
          # 创建临时文件
          tmp_file=$(mktemp)
          
          # 读取README.md直到"### 3. 使用生成的直播源"这一行
          sed '/### 3. 使用生成的直播源/q' README.md > "$tmp_file"
          
          # 添加更新的内容
          cat >> "$tmp_file" << EOF
          - 最近更新时间：\`$current_time\`
          - 直接访问：
            - M3U格式：[\`result.m3u\`](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/output/result.m3u)
            - TXT格式：[\`result.txt\`](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/output/result.txt)
          - CDN加速：
            - M3U格式：[\`result.m3u\`](https://cdn.jsdelivr.net/gh/$GITHUB_REPOSITORY@main/output/result.m3u)
            - TXT格式：[\`result.txt\`](https://cdn.jsdelivr.net/gh/$GITHUB_REPOSITORY@main/output/result.txt)
          - HTTP测速结果：
            - M3U格式：[\`result_http_test.m3u\`](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/output/result_http_test.m3u)
            - TXT格式：[\`result_http_test.txt\`](https://raw.githubusercontent.com/$GITHUB_REPOSITORY/main/output/result_http_test.txt)

          ## 最佳实践
          EOF
          
          # 从"## 最佳实践"开始的内容追加到临时文件
          sed -n '/^## 最佳实践/,$p' README.md >> "$tmp_file"
          
          # 替换原始文件
          mv "$tmp_file" README.md

      - name: Commit and push changes
        run: |
          # 配置git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 添加所有更改到暂存区
          git add .
          
          # 保存工作区状态
          git stash save "Temporary save"
          
          # 同步远程更改
          git pull origin main --rebase
          
          # 恢复工作区状态
          git stash pop
          
          # 重新添加所有文件
          git add output/result.m3u
          git add output/result.txt
          git add output/result_http_test.m3u
          git add output/result_http_test.txt
          git add README.md
          
          # 检查是否有更改需要提交
          if ! git diff --staged --quiet; then
            echo "Committing and pushing changes to the repository..."
            git commit -m "Update IPTV files and README (包含两次测速结果) - $(date '+%Y-%m-%d %H:%M:%S')"
            # 使用token进行推送
            git push "https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
